### ISSUE TITLE
[meta] new version requirements

### ISSUE THREAD

**Issue by paulrouget** [aclap-dev/vdhcoapp#155]
- [x] recent ffmpeg builds based on https://github.com/aclap-dev/ffmpeg-static-builder
- [x] use better ffmpeg output options for stdout parsing
- [x] remove any support of ffplay
- [x] provide a faster `fs.write` implementation
- [x] update to Node 18 (esbuild + pkg)
- [x] Experiment with static glib / test with old Ubuntu
- [x] introduce basic test infra
- [x] Auto-install manifest at startup for DMG (as user, need to be tested)
- [x] https://github.com/aclap-dev/vdhcoapp/issues/102
- [ ] Flatpack issues:
  - https://github.com/aclap-dev/vdhcoapp/issues/151
  - https://github.com/aclap-dev/vdhcoapp/issues/139
  - https://github.com/aclap-dev/vdhcoapp/issues/137
  - https://github.com/aclap-dev/vdhcoapp/issues/136
  - https://github.com/aclap-dev/vdhcoapp/issues/114 
- [x] Mac issues:
  - https://github.com/aclap-dev/vdhcoapp/issues/50
  - https://github.com/aclap-dev/vdhcoapp/issues/115
  - https://github.com/aclap-dev/vdhcoapp/issues/150
  - https://github.com/aclap-dev/vdhcoapp/pull/108
  - [x] make sure installers are properly signed on mac
- [x] https://github.com/aclap-dev/vdhcoapp/issues/146
- [x] Publish for:
    - Linux x64 glibc 2.17 (drop 32 bits support)
    - Mac OS Intel
    - Mac OS Arm
    - Windows Intel 64 bits
- Should we support Windows and Linux Arm?
- See if it's possible to build a universal binary for Mac

**Comment by paulrouget** [comment]
Note for later:

The warning:

```
> Warning Cannot resolve 'adapters[adapter]'
  /Users/paul/downloadhelper/coapp/dist2/main.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
```

Comes from: https://github.com/jaredwray/keyv/blob/a5528c4c5c3aeef34c8570cfb4f102a834322672/packages/keyv/src/index.js#L22

Gonna assume that only Map is necessary and ignore this warning.

**Comment by paulrouget** [comment]
- [ ] format test fails on Linux but not on Mac.

**Comment by paulrouget** [comment]
I think we good. The only issue I haven't figured out is flatpak for chrome based browser. See README.
